# Shell variables
# Generated by 'wal'
wallpaper='/home/lyneca/Downloads/samuel-ferrara-1527pjeb6jg-unsplash.jpg'

# Special
background='#0f1118'
foreground='#e5d0cb'
cursor='#e5d0cb'

# Colors
color0='#0f1118'
color1='#57698A'
color2='#607195'
color3='#6D7593'
color4='#8A7A8B'
color5='#7888A9'
color6='#9A97AE'
color7='#e5d0cb'
color8='#a0918e'
color9='#57698A'
color10='#607195'
color11='#6D7593'
color12='#8A7A8B'
color13='#7888A9'
color14='#9A97AE'
color15='#e5d0cb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
