--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/lyneca/Downloads/samuel-ferrara-1527pjeb6jg-unsplash.jpg"

-- Special
background="#0f1118"
foreground="#e5d0cb"
cursor="#e5d0cb"

-- Colors
color0="#0f1118"
color1="#57698A"
color2="#607195"
color3="#6D7593"
color4="#8A7A8B"
color5="#7888A9"
color6="#9A97AE"
color7="#e5d0cb"
color8="#a0918e"
color9="#57698A"
color10="#607195"
color11="#6D7593"
color12="#8A7A8B"
color13="#7888A9"
color14="#9A97AE"
color15="#e5d0cb"
